# Azure Web Apps Deployment Workflow - Atualizado 2025
# Node 20 + Angular + GitHub Actions + Azure (Windows)

name: Build and deploy Angular app to Azure Web App - app-wisetraining-web-test

on:
  push:
    branches:
      - microfrontend
  workflow_dispatch:

jobs:
  build:
    name: Build Angular App
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3. Instalar dependências e buildar
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present

      # 4. Preparar pacote de deploy
      - name: Prepare deployment package
        run: |
          mkdir deploy
          copy web.config deploy\
          xcopy dist\WebTemplate\browser\* deploy\ /E /I /Y

      # 5. Upload artefato
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: deploy/

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build

    steps:
      # 1. Baixar artefato
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app
          path: deploy

      # 2. Listar conteúdo (debug)
      - name: List deploy folder contents
        run: |
          Write-Host 'Contents of deploy:'
          Get-ChildItem -Path deploy -Recurse | ForEach-Object { Write-Host $_.FullName }
        shell: powershell

      # 3. Criar ZIP
      - name: Create deploy ZIP
        run: |
          if (Test-Path deploy.zip) { Remove-Item deploy.zip -Force }
          Compress-Archive -Path deploy\* -DestinationPath deploy.zip
        shell: powershell

      # 4. Deploy para Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-wisetraining-web-test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_123928CE6AA448218F8BE3880898BC8F }}
          package: deploy.zip
