# Azure Web Apps Deployment Workflow - Atualizado 2025
# Docs: https://github.com/Azure/webapps-deploy
# Node 20 + Angular + GitHub Actions + Azure

name: Build and deploy Node.js app to Azure Web App - app-wisetraining-web-test

on:
  push:
    branches:
      - microfrontend
  workflow_dispatch:

jobs:
  build:
    name: Build Angular App
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout do repositório
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3. Instalar dependências, buildar e testar
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present
          if [ -f "karma.conf.js" ]; then npx ng test --watch=false --browsers=ChromeHeadless; fi

      # 4. Upload artefato gerado
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: dist/

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build

    steps:
      # 1. Baixar artefato da build
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app
          path: .

      # 2. Deploy para Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-wisetraining-web-test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_123928CE6AA448218F8BE3880898BC8F }}
          package: .
